# Configuration for train.py


# Set global seed
set_seed: 42

# Set number of workers (int | float)
num_workers: 0.8

# Config dataset
data:
  data_path: qlstm/data/place_1_new.xlsx
  batch_size: 1
  time_steps: 1
  overlap: false
  data_limit: null
  split_size: [0.7, 0.3, 0]

# Config model
model:
  checkpoint: null

# Config optimizer
optimizer:
  lr: 1e-3

# Config scheduler
scheduler:
  warmup_epochs: 3
  start_factor: 0.01

# Config trainer
trainer:
  accelerator: auto
  max_epochs: 25
  precision: 32-true
  gradient_clip_val: null

# Config logger
logger:
  save_dir: ./lightning_logs
  name: LSTM
  version: null
