# Configuration for train.py


# Set global seed
set_seed: 42

# Set number of workers (int | float)
num_workers: 0.8

# Config dataset
data:
  data_path: qlstm/data/place_1_new.xlsx
  batch_size: 32
  time_steps: 6
  data_limit: null
  split_size: [0.7, 0.2, 0.1]

# Config model
model:
  checkpoint: null
  pretrained: false
  freeze: false

# Config optimizer
optimizer:
  lr: 1e-3

# Config scheduler
scheduler:
  warmup_epochs: 5
  start_factor: 0.01

# Config trainer
trainer:
  accelerator: cpu
  max_epochs: 50
  precision: 32-true
  gradient_clip_val: null
